[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","UP","N","B"]
exclude = ["frontend", ".venv", "dist", "build"]

[tool.pytest.ini_options]
pythonpath = ["backend"]
addopts = "-q"
