name: ci
on:
  push: { branches: [ main ] }
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r backend/requirements.txt || true
      - run: pip install fastapi uvicorn[standard] pydantic pydantic-settings pandas numpy pytest ruff mypy
      - run: ruff check backend
      - run: mypy --ignore-missing-imports backend || true
      - run: pytest backend/tests -q
